FROM debian:stable AS snapbase
LABEL maintainer "Matt Dickinson"

ARG S6_OVERLAY_VERSION=3.1.4.2
ENV ARCH=armhf

RUN apt-get update && apt-get install -y \
	alsa-utils \
	avahi-daemon \
	git \
	libasound2-dev \
	libpulse-dev \
	libvorbisidec-dev \
	libvorbis-dev \
	libopus-dev \
	libflac-dev \
	libsoxr-dev \
	libavahi-client-dev \
	libexpat1-dev \
	mosquitto-clients \
	nano \
	wget \
	xz-utils \
#	gcc
	snapclient	

WORKDIR /


ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${ARCH}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-${ARCH}.tar.xz

WORKDIR /

ENV TZ=America/New_York
ENV SNAPCLIENT_SOUNDCARD ""
ENV SNAPCLIENT_HOST ""
ENV HOSTID ""


CMD snapclient \
    --host "$SNAPCLIENT_HOST" \
    --soundcard "$SNAPCLIENT_SOUNDCARD" \
    --hostID "$HOSTID"	

